---
title: "report-dimensional-analysis"
output: html_document
params:
  dim_class: dim_class
  pca_variants_plot: pca_variants_plot
  pca_variants_stat: pca_variants_stat
---

```{r setup, echo = FALSE, include=FALSE}
require(rmarkdown)
require(htmltools)
require(R6)
require(patchwork)
knitr::opts_chunk$set(echo = TRUE)
```




```{r, echo=FALSE}
summary(params$dim_class$pca_results) %>% 
  .[6] %>% .[[1]] %>% 
  as.data.frame() %>% 
  paged_table()
```

```{r, echo=FALSE, fig.width = 12}
(params$dim_class$skew_plot_res + params$dim_class$biplot_res)
```

```{r, echo=FALSE, fig.height=8, fig.width = 12}
(params$dim_class$pca_plot_res)
```

```{r, echo=FALSE}
paged_table(params$dim_class$pca_results$rotation %>% as.data.frame())
paged_table(params$dim_class$pc_statistics_res)
```


```{r, echo=FALSE}
paged_table(params$dim_class$lda_summary_res)
```

```{r, echo=FALSE,  fig.height=10, fig.width = 12}
params$dim_class$conf_mat_plot_res +
  params$dim_class$lda_hist_res +
  params$dim_class$roc_curve_res +
  params$dim_class$lda_classification_plot_res
```


```{r, echo=FALSE}
params$dim_class$lda_statistics_res
```

### Result of dimensionality analysis on variants from significant models.

```{r, echo=FALSE, fig.height=8, fig.width = 12}
(params$pca_variants_plot)
```

```{r, echo=FALSE}
paged_table(params$pca_variants_stat)
```


